spring:
  application:
    name: spring-ai-02-image

  ai:
    zhipuai:
      base-url: https://open.bigmodel.cn/api/paas
      api-key: your-api-key
      image:
        options:
          model: cogview-4-250304


