spring:
  application:
    name: spring-ai-01-chat
  profiles:
    active: deepseek



---

spring:
  config:
    activate:
      on-profile: deepseek
  ai:
    openai:
      api-key: sk-your-api-key
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
      embedding:
        enabled: false


---

spring:
  config:
    activate:
      on-profile: qwen
  ai:
    openai:
      api-key: sk-your-api-key
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen-vl-max-latest
      embedding:
        enabled: false
